CI macOS: allow 'brew upgrade' to fail

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -67,10 +67,11 @@ jobs:
         # - dyld[45184]: Library not loaded: '/usr/local/opt/libunistring/lib/libunistring.2.dylib'
         #   Referenced from: '/usr/local/Cellar/wget/1.21.3/bin/wget'
         #   Reason: tried: '/usr/local/opt/libunistring/lib/libunistring.2.dylib' (no such file),
+        # Note: brew upgrade does fail regularly, but brew is anyway in a better state afterwards
         run: |
           brew cleanup
           brew update
-          brew upgrade
+          brew upgrade || true
 
       - name: Install homebrew packages required by main script
         run: brew install wget
